### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by FS1360472174** [FS1360472174/javaweb#81]
https://github.com/alibaba/p3c/blob/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E7%BA%AA%E5%BF%B5%E7%89%88%EF%BC%89.pdf

**Comment by FS1360472174** [comment]
String str = "a,b,c,,";
最后一个分隔符需要判断是否有内容

**Comment by FS1360472174** [comment]
<? extends T>频繁向外
<? super T>频繁写入

**Comment by FS1360472174** [comment]
ArrayList 循环中remove数据
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at Test.main(Test.java:13)

**Comment by FS1360472174** [comment]
多层条件使用策略模式，状态模式重构

**Comment by FS1360472174** [comment]
mysql

consts: 匹配一行
ref: 普通索引
range: 索引范围

count(*） 统计包括null的行

count（distinct col） 统计除Null以外
都是SQL92标准，与具体数据库无关

**Comment by FS1360472174** [comment]
TCP协议time_wait时间默认240s，
高并发环境下，建议改小/etc/sysctl.conf
net.ipv4.tcp_fin_timeout=30
